### ISSUE TITLE
Maybe make these getters or setters

### ISSUE THREAD

**Issue by TroyCalaquian** [COMP2522/project-space-invaders#103]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Constant.java#L1

On one hand, I think this is smart. On the other, directly grabbing them like this doesn't seem good.

**Comment by 7374179** [comment]
done
