### ISSUE TITLE
SimplifymissileInvaderFireAtBarrier method

### ISSUE THREAD

**Issue by gurtejx** [COMP2522/project-space-invaders#108]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/MissileInvader.java#L71

This method can be fitted into one line of code as : 

return (this.yPos < Constant.Y_POS_BARRIER + Constant.HEIGHT_BARRIER
            && this.yPos + this.height > Constant.Y_POS_BARRIER);

**Comment by 7374179** [comment]
fixed
