### ISSUE TITLE
Remove unnecessary getters and setters

### ISSUE THREAD

**Issue by gurtejx** [COMP2522/project-space-invaders#111]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Sprite.java#L4

This class has various getters and setters that are not being used. Consider removing them as they make the class too crowded.

**Comment by 7374179** [comment]
fixed
