### ISSUE TITLE
Simplify keyPressed method

### ISSUE THREAD

**Issue by gurtejx** [COMP2522/project-space-invaders#112]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Keyboard.java#L31

Consider using switch statement instead of if-else blocks to write clean code.

Also, the first 'if' condition can be simply checked by writing 'Window.player.isAlive()' instead of 'Window.player.isAlive() == true'

**Comment by 7374179** [comment]
fixed
