### ISSUE TITLE
Create several methods into Sprite class

### ISSUE THREAD

**Issue by Bingdididi** [COMP2522/project-space-invaders#21]
+ Sprite(PVector position, PVector direction, float size, float speed, Color color, Window window);

+ collide(): void
+ getDirection(): PVector
+ getPosition(): PVector
+ update(): void
+ getSize(): float
+ collided(Sprite a, Sprite b): boolean
+ draw(): void
+ setDirection(PVector direction): void
+ hashCode(): int
+ compareTo(Object o): int
+ equals(Object o): boolean

**Comment by 7374179** [comment]
done
