### ISSUE TITLE
Create an enum or constant for font sizes on these lines

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-space-invaders#52]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Window.java#L28

https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Window.java#L30

**Comment by 7374179** [comment]
done
