### ISSUE TITLE
This findBrick is similatr to findTopBrick, maybe combine them

### ISSUE THREAD

**Issue by VietNguyenSet1D** [COMP2522/project-space-invaders#57]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Barrier.java#L131

**Comment by YejuJ** [comment]
findBrick() is associated with the Player's missile hits, and findTopBrick is associated with the Invader's missile hits. So I think we need both methods to track each hit from the different class objects.
