### ISSUE TITLE
removeBrick is similar to removeTopBrick, combine them if you can

### ISSUE THREAD

**Issue by VietNguyenSet1D** [COMP2522/project-space-invaders#58]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Barrier.java#L145

**Comment by YejuJ** [comment]
Same as findBrick(), we need both methods since they track of the missile hits from different class objects.
