### ISSUE TITLE
breakBrick is similar to breakTopBrick, combine them if you can

### ISSUE THREAD

**Issue by VietNguyenSet1D** [COMP2522/project-space-invaders#60]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Barrier.java#L163

**Comment by YejuJ** [comment]
Same as findBrick(), removeBrick(). We need both of them.
