### ISSUE TITLE
Methods shouldn't have side effects, they should be in their own methods

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-space-invaders#74]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/MissilePlayer.java#L89

**Comment by 7374179** [comment]
public void playInvaderDeadSound() {
    Audio.playSound("/InvaderDead.wav");
  }

done
