### ISSUE TITLE
Make the constructor private

### ISSUE THREAD

**Issue by TroyCalaquian** [COMP2522/project-space-invaders#99]
https://github.com/COMP2522/project-space-invaders/blob/c6f19b2131e73dd52b2f1ef2a2200902a7f8e7bf/space_invader_game/src/main/java/org/space/invader/Audio.java#L20

If you're going to call the constructor through a public static class, I think it might be good if you made the constructor itself private. Because right now, you could just make a audio object, then use its play method to play the sound.

**Comment by teihyung** [comment]
ok will do
